import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '../../theme/theme';
import { Card, IconBox, Logo, PrimaryButton, Screen, SmartImage } from '../components/UI';
import { media } from '../../data/media';
import { useHomeViewModel } from '../../viewmodels/useHomeViewModel';
export default function HomeScreen({navigation,session}) { const vm=useHomeViewModel(session); const actions=[['chatbubble-ellipses-outline','Talk to a Counsellor','blue','Counsellors'],['people-outline','Peer Support','green','PeerSupport'],['book-outline','Psychoeducation','purple','Library'],['git-branch-outline','Referrals','teal','Referrals']]; return <Screen>
  <View style={s.top}><Logo small/><Pressable onPress={()=>navigation.navigate('Crisis')}><Ionicons name="notifications-outline" size={23} color={colors.text}/></Pressable></View>
  <Text style={s.hello}>Hello, {vm.greeting}</Text><Text style={s.sub}>Take a small step today. Your wellbeing matters.</Text>
  <Card style={s.hero}><SmartImage source={media.heroTherapy} fallback={require('../../../assets/mental-illustration.png')} style={s.heroImage}/><View style={s.heroOverlay}><Text style={s.heroTitle}>A safe place to be heard</Text><Text style={s.heroText}>Private support, practical resources and trusted referrals.</Text></View></Card>
  <Card style={s.safe}><IconBox icon="shield-checkmark" tone="green" size={44}/><View style={{flex:1,marginLeft:12}}><Text style={s.safeTitle}>Private by design</Text><Text style={s.safeText}>Use an anonymous identity and choose what you share.</Text></View></Card>
  <Text style={s.section}>How can we support you?</Text><View style={s.grid}>{actions.map(([icon,title,tone,target])=><Card key={title} style={s.action} onPress={()=>navigation.navigate(target)}><IconBox icon={icon} tone={tone}/><Text style={s.actionTitle}>{title}</Text><Ionicons name="chevron-forward" size={18} color={colors.muted}/></Card>)}</View>
  {vm.upcoming.length ? <Card><View style={s.row}><Text style={s.section2}>Upcoming session</Text><Pressable onPress={()=>navigation.navigate('Sessions')}><Text style={s.link}>View all</Text></Pressable></View><Text style={s.sessionName}>{vm.upcoming[0].counsellorName}</Text><Text style={s.sessionMeta}>{vm.upcoming[0].date} • {vm.upcoming[0].time} • {vm.upcoming[0].mode}</Text></Card> : null}
  <Card style={s.crisis}><View style={{flex:1}}><Text style={s.crisisTitle}>Need urgent help?</Text><Text style={s.crisisText}>For immediate danger, use the emergency support screen.</Text></View><PrimaryButton title="Get help" danger onPress={()=>navigation.navigate('Crisis')}/></Card>
</Screen> }
const s=StyleSheet.create({top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:23},hello:{fontSize:27,fontWeight:'900',color:colors.text},sub:{color:colors.muted,fontSize:14,marginTop:5,marginBottom:18},hero:{padding:0,overflow:'hidden',height:190,backgroundColor:'#0D3E83'},heroImage:{width:'100%',height:'100%',opacity:.72},heroOverlay:{position:'absolute',left:18,right:18,bottom:18},heroTitle:{fontSize:19,fontWeight:'900',color:'#fff'},heroText:{fontSize:12,lineHeight:18,color:'#F2F7FF',marginTop:4,maxWidth:280},safe:{flexDirection:'row',alignItems:'center',marginTop:6},safeTitle:{fontWeight:'900',color:colors.text},safeText:{fontSize:12,color:colors.muted,marginTop:3},section:{fontSize:17,fontWeight:'900',color:colors.text,marginTop:12,marginBottom:12},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between'},action:{width:'48%',minHeight:140,justifyContent:'space-between'},actionTitle:{fontSize:14,fontWeight:'800',color:colors.text,marginTop:9},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},section2:{fontSize:15,fontWeight:'900',color:colors.text},link:{color:colors.primary,fontWeight:'800',fontSize:12},sessionName:{fontSize:14,fontWeight:'800',marginTop:12,color:colors.text},sessionMeta:{fontSize:12,color:colors.muted,marginTop:4},crisis:{marginTop:5,borderColor:'#F3D0CD',backgroundColor:colors.redSoft},crisisTitle:{fontWeight:'900',color:colors.text,fontSize:15},crisisText:{fontSize:12,color:colors.muted,marginVertical:5}});
