import React from 'react';
import { Alert, StyleSheet, Switch, Text, View } from 'react-native';
import { colors } from '../../theme/theme';
import { Card, Header, IconBox, PrimaryButton, Screen } from '../components/UI';
import { useAuthViewModel } from '../../viewmodels/useAuthViewModel';
import { useProfileViewModel } from '../../viewmodels/useProfileViewModel';
export default function ProfileScreen({navigation,session,setSession}) { const auth=useAuthViewModel(setSession); const vm=useProfileViewModel({session,setSession}); const toggle=async()=>vm.update({notifications:!session.notifications}); return <Screen><Header title="Profile & settings"/><Card style={s.profile}><IconBox icon="person-outline" tone="blue" size={68}/><Text style={s.name}>{session.displayName}</Text><Text style={s.id}>Anonymous ID • {session.anonymousId}</Text></Card><Card><Row icon="calendar-outline" title="My sessions" onPress={()=>navigation.navigate('Sessions')}/><Row icon="git-branch-outline" title="My referrals" onPress={()=>navigation.navigate('Referrals')}/><Row icon="language-outline" title="Language" value={session.language} onPress={()=>navigation.navigate('Language')}/><View style={s.divider}/><View style={s.row}><IconBox icon="notifications-outline" tone="purple" size={40}/><View style={{flex:1,marginLeft:11}}><Text style={s.rowTitle}>Notifications</Text><Text style={s.rowSub}>Session and support reminders</Text></View><Switch value={!!session.notifications} onValueChange={toggle} trackColor={{true:'#9BC4FF'}} thumbColor={session.notifications?colors.primary:'#fff'}/></View></Card><Card><Text style={s.privacyTitle}>Privacy & safety</Text><Text style={s.privacyText}>MindBridge is designed around anonymous access. This prototype stores data locally. Production must implement secure authentication, encrypted storage, access controls and approved clinical governance.</Text></Card><PrimaryButton title="Sign out" danger onPress={()=>Alert.alert('Sign out','Your local session will be removed from this device.',[{text:'Cancel',style:'cancel'},{text:'Sign out',style:'destructive',onPress:auth.logout}])}/></Screen> }
function Row({icon,title,value,onPress}){const {Ionicons}=require('@expo/vector-icons');return <View style={s.rowWrap}><IconBox icon={icon} tone="blue" size={40}/><View style={{flex:1,marginLeft:11}}><Text style={s.rowTitle}>{title}</Text>{value?<Text style={s.rowSub}>{value}</Text>:null}</View><Text onPress={onPress} style={s.chevron}>›</Text></View>}
const s=StyleSheet.create({profile:{alignItems:'center',paddingVertical:23},name:{fontSize:20,fontWeight:'900',color:colors.text,marginTop:10},id:{fontSize:11,color:colors.muted,marginTop:4},rowWrap:{flexDirection:'row',alignItems:'center',paddingVertical:8},row:{flexDirection:'row',alignItems:'center'},rowTitle:{fontSize:13,fontWeight:'800',color:colors.text},rowSub:{fontSize:10,color:colors.muted,marginTop:3},chevron:{fontSize:25,color:colors.muted,paddingHorizontal:5},divider:{height:1,backgroundColor:colors.border,marginVertical:8},privacyTitle:{fontSize:14,fontWeight:'900',color:colors.text},privacyText:{fontSize:11,lineHeight:18,color:colors.muted,marginTop:6}});
